export * from './text';
import * as StrUtil from 'str-util';
import { enspace } from './text';
import tiebaHarmony from 'tieba-harmony';
import chkBlankLine from 'blank-line';
export { StrUtil };
export { chkBlankLine };
export { tiebaHarmony };
export declare const novelText: enspace;
export default novelText;
