/**
 * do not edit this file
 */

export const enum EnumHtmlTag
{
	OPEN = '&lt;|\\u003C|＜',
	CLOSE = '&gt;|\\u003E|＞',
}

export type IAllowedHtmlTagList = "s" | "ruby" | "i" | "b" | "sup" | "sub";

export const allowedHtmlTagList = Object.freeze([
	"s",
	"ruby",
	"i",
	"b",
	"sup",
	"sub"
] as const);

export const reTxtHtmlTag = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([sｓ]|[rｒ][uｕ][bｂ][yｙ]|[iｉ]|[bｂ]|[sｓ][uｕ][pｐ]|[sｓ][uｕ][bｂ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;
export const reHtmlRubyRt = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([rｒ][tｔ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;
export const reHtmlRubyRp = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([rｒ][pｐ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;

export const reHtmlTagOpen = /[&＆][lｌ][tｔ][;；]|\u003C|[<＜]/giu;
export const reHtmlTagClose = /[&＆][gｇ][tｔ][;；]|\u003E|[>＞]/giu;

export const reTxtImgTag = /[(（](?:[挿插揷](?:[図图圖]|[划劃画畫]|[絵繪绘])|[図图圖](?:片|[像象])|[划劃画畫][像象]|[iｉ][mｍ][gｇ]|[iｉ][mｍ][aａ][gｇ][eｅ]|[pｐ][hｈ][oｏ][tｔ][oｏ]|[iｉ][lｌ][lｌ][uｕ][sｓ])([a-z0-9ａ-ｚ０-９_―—─－一⸺̲̱ˍ﹘\-]+)[)）]/giu;

