/**
 * do not edit this file
 */
export declare const enum EnumHtmlTag {
    OPEN = "&lt;|\\u003C|\uFF1C",
    CLOSE = "&gt;|\\u003E|\uFF1E"
}
export declare type IAllowedHtmlTagList = "s" | "ruby" | "i" | "b" | "sup" | "sub";
export declare const allowedHtmlTagList: readonly ["s", "ruby", "i", "b", "sup", "sub"];
export declare const reTxtHtmlTag: RegExp;
export declare const reHtmlRubyRt: RegExp;
export declare const reHtmlRubyRp: RegExp;
export declare const reHtmlTagOpen: RegExp;
export declare const reHtmlTagClose: RegExp;
export declare const reTxtImgTag: RegExp;
