"use strict";
/**
 * do not edit this file
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.reTxtImgTag = exports.reHtmlTagClose = exports.reHtmlTagOpen = exports.reHtmlRubyRp = exports.reHtmlRubyRt = exports.reTxtHtmlTag = exports.allowedHtmlTagList = exports.EnumHtmlTag = void 0;
var EnumHtmlTag;
(function (EnumHtmlTag) {
    EnumHtmlTag["OPEN"] = "&lt;|\\u003C|\uFF1C";
    EnumHtmlTag["CLOSE"] = "&gt;|\\u003E|\uFF1E";
})(EnumHtmlTag = exports.EnumHtmlTag || (exports.EnumHtmlTag = {}));
exports.allowedHtmlTagList = Object.freeze([
    "s",
    "ruby",
    "i",
    "b",
    "sup",
    "sub"
]);
exports.reTxtHtmlTag = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([sｓ]|[rｒ][uｕ][bｂ][yｙ]|[iｉ]|[bｂ]|[sｓ][uｕ][pｐ]|[sｓ][uｕ][bｂ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;
exports.reHtmlRubyRt = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([rｒ][tｔ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;
exports.reHtmlRubyRp = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([rｒ][pｐ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;
exports.reHtmlTagOpen = /[&＆][lｌ][tｔ][;；]|\u003C|[<＜]/giu;
exports.reHtmlTagClose = /[&＆][gｇ][tｔ][;；]|\u003E|[>＞]/giu;
exports.reTxtImgTag = /[(（](?:[挿插揷](?:[図图圖]|[划劃画畫]|[絵繪绘])|[図图圖](?:片|[像象])|[划劃画畫][像象]|[iｉ][mｍ][gｇ]|[iｉ][mｍ][aａ][gｇ][eｅ]|[pｐ][hｈ][oｏ][tｔ][oｏ]|[iｉ][lｌ][lｌ][uｕ][sｓ])([a-z0-9ａ-ｚ０-９_―—─－一⸺̲̱ˍ﹘\-]+)[)）]/giu;
//# sourceMappingURL=tags.js.map