/**
 * 文字標籤定義
 * Text Tag Definitions
 *
 * 此檔案定義了解析器支援的 HTML 標籤和相關正則表達式。
 * This file defines HTML tags supported by the parser and related regular expressions.
 *
 * 注意：請勿編輯此檔案 / Note: Do not edit this file
 *
 * @module parse-txt-tag/lib/tags
 */

/**
 * HTML 標籤枚舉
 * HTML Tag Enum
 *
 * 定義標籤的開啟和關閉符號模式。
 * Defines opening and closing tag symbol patterns.
 */
export const enum EnumHtmlTag
{
	/**
	 * 開啟標籤符號模式
	 * Opening tag symbol pattern
	 *
	 * 支援 &lt;, Unicode, 和全形符號
	 * Supports &lt;, Unicode, and full-width symbols
	 */
	OPEN = '&lt;|\\u003C|＜',

	/**
	 * 關閉標籤符號模式
	 * Closing tag symbol pattern
	 *
	 * 支援 &gt;, Unicode, 和全形符號
	 * Supports &gt;, Unicode, and full-width symbols
	 */
	CLOSE = '&gt;|\\u003E|＞',
}

/**
 * 允許的 HTML 標籤列表類型
 * Allowed HTML Tag List Type
 *
 * 定義解析器支援的 HTML 標籤名稱。
 * Defines HTML tag names supported by the parser.
 */
export type IAllowedHtmlTagList = "s" | "ruby" | "i" | "b" | "sup" | "sub";

/**
 * 允許的 HTML 標籤列表
 * Allowed HTML Tag List
 *
 * 凍結的標籤名稱陣列，用於驗證和迭代。
 * Frozen array of tag names for validation and iteration.
 */
export const allowedHtmlTagList = Object.freeze([
	// 刪除線 / Strikethrough
	"s",
	// Ruby 註釋 / Ruby annotation
	"ruby",
	// 斜體 / Italic
	"i",
	// 粗體 / Bold
	"b",
	// 上標 / Superscript
	"sup",
	// 下標 / Subscript
	"sub"
] as const);

/**
 * 文字 HTML 標籤匹配正則
 * Text HTML Tag Matching Regex
 *
 * 匹配文字中的 HTML 標籤，支援全形和半形字元。
 * Matches HTML tags in text, supporting full-width and half-width characters.
 */
export const reTxtHtmlTag = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([sｓ]|[rｒ][uｕ][bｂ][yｙ]|[iｉ]|[bｂ]|[sｓ][uｕ][pｐ]|[sｓ][uｕ][bｂ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;

/**
 * HTML Ruby Rt 標籤匹配正則
 * HTML Ruby Rt Tag Matching Regex
 *
 * 匹配 ruby 標籤內的 rt 標籤。
 * Matches rt tags within ruby tags.
 */
export const reHtmlRubyRt = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([rｒ][tｔ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;

/**
 * HTML Ruby Rp 標籤匹配正則
 * HTML Ruby Rp Tag Matching Regex
 *
 * 匹配 ruby 標籤內的 rp 標籤。
 * Matches rp tags within ruby tags.
 */
export const reHtmlRubyRp = /(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])([rｒ][pｐ])((?:\s+[\w \t＝═=ａ-ｚ０-９]*?)?)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])([^\n]*?)(?:[&＆][lｌ][tｔ][;；]|\u003C|[<＜])(?:(?:[\/／])\1)(?:[&＆][gｇ][tｔ][;；]|\u003E|[>＞])/giu;

/**
 * HTML 開啟標籤匹配正則
 * HTML Opening Tag Matching Regex
 *
 * 匹配所有形式的開啟標籤符號。
 * Matches all forms of opening tag symbols.
 */
export const reHtmlTagOpen = /[&＆][lｌ][tｔ][;；]|\u003C|[<＜]/giu;

/**
 * HTML 關閉標籤匹配正則
 * HTML Closing Tag Matching Regex
 *
 * 匹配所有形式的關閉標籤符號。
 * Matches all forms of closing tag symbols.
 */
export const reHtmlTagClose = /[&＆][gｇ][tｔ][;；]|\u003E|[>＞]/giu;

/**
 * 文字圖片標籤匹配正則
 * Text Image Tag Matching Regex
 *
 * 匹配各種格式的圖片標記，包括中日文和英文。
 * Matches image tags in various formats, including Chinese, Japanese, and English.
 *
 * 支援格式 / Supported formats:
 * - (插圖id), (挿絵id), (図片id)
 * - (img id), (image id), (photo id)
 */
export const reTxtImgTag = /[(（](?:[挿插揷](?:[図图圖]|[划劃画畫]|[絵繪绘])|[図图圖](?:片|[像象])|[划劃画畫][像象]|[iｉ][mｍ][gｇ]|[iｉ][mｍ][aａ][gｇ][eｅ]|[pｐ][hｈ][oｏ][tｔ][oｏ]|[iｉ][lｌ][lｌ][uｕ][sｓ])([a-z0-9ａ-ｚ０-９_―—─－一⸺̲̱ˍ﹘\-]+)[)）]/giu;

